# GitHub Pages настройки
title: "Wplace Timelapse - Томск"
description: "Таймлапс центра Томска в реальном времени"
url: "https://YOUR_USERNAME.github.io"
baseurl: "/wplace-tomsk-timelapse"

# Включаем обработку файлов в docs/
include:
  - "*.json"
  - "*.png"
  - "*.mp4"
  - "*.gif"
